// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transfer.proto

package force_transfer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type TransferRequest struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Memo                 string   `protobuf:"bytes,4,opt,name=memo,proto3" json:"memo,omitempty"`
	Trxid                string   `protobuf:"bytes,5,opt,name=trxid,proto3" json:"trxid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferRequest) Reset()         { *m = TransferRequest{} }
func (m *TransferRequest) String() string { return proto.CompactTextString(m) }
func (*TransferRequest) ProtoMessage()    {}
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_3ea359c18e44b03b, []int{0}
}
func (m *TransferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferRequest.Unmarshal(m, b)
}
func (m *TransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferRequest.Marshal(b, m, deterministic)
}
func (dst *TransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferRequest.Merge(dst, src)
}
func (m *TransferRequest) XXX_Size() int {
	return xxx_messageInfo_TransferRequest.Size(m)
}
func (m *TransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransferRequest proto.InternalMessageInfo

func (m *TransferRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *TransferRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *TransferRequest) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *TransferRequest) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *TransferRequest) GetTrxid() string {
	if m != nil {
		return m.Trxid
	}
	return ""
}

// The response message containing the greetings
type TransferReply struct {
	Reply                string   `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferReply) Reset()         { *m = TransferReply{} }
func (m *TransferReply) String() string { return proto.CompactTextString(m) }
func (*TransferReply) ProtoMessage()    {}
func (*TransferReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_3ea359c18e44b03b, []int{1}
}
func (m *TransferReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferReply.Unmarshal(m, b)
}
func (m *TransferReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferReply.Marshal(b, m, deterministic)
}
func (dst *TransferReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferReply.Merge(dst, src)
}
func (m *TransferReply) XXX_Size() int {
	return xxx_messageInfo_TransferReply.Size(m)
}
func (m *TransferReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferReply.DiscardUnknown(m)
}

var xxx_messageInfo_TransferReply proto.InternalMessageInfo

func (m *TransferReply) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func (m *TransferReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*TransferRequest)(nil), "force_transfer.TransferRequest")
	proto.RegisterType((*TransferReply)(nil), "force_transfer.TransferReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GrpcTransferClient is the client API for GrpcTransfer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpcTransferClient interface {
	// Sends a greeting
	RpcSendaction(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferReply, error)
}

type grpcTransferClient struct {
	cc *grpc.ClientConn
}

func NewGrpcTransferClient(cc *grpc.ClientConn) GrpcTransferClient {
	return &grpcTransferClient{cc}
}

func (c *grpcTransferClient) RpcSendaction(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferReply, error) {
	out := new(TransferReply)
	err := c.cc.Invoke(ctx, "/force_transfer.grpc_transfer/rpc_sendaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcTransferServer is the server API for GrpcTransfer service.
type GrpcTransferServer interface {
	// Sends a greeting
	RpcSendaction(context.Context, *TransferRequest) (*TransferReply, error)
}

func RegisterGrpcTransferServer(s *grpc.Server, srv GrpcTransferServer) {
	s.RegisterService(&_GrpcTransfer_serviceDesc, srv)
}

func _GrpcTransfer_RpcSendaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcTransferServer).RpcSendaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/force_transfer.grpc_transfer/RpcSendaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcTransferServer).RpcSendaction(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GrpcTransfer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "force_transfer.grpc_transfer",
	HandlerType: (*GrpcTransferServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "rpc_sendaction",
			Handler:    _GrpcTransfer_RpcSendaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transfer.proto",
}

func init() { proto.RegisterFile("transfer.proto", fileDescriptor_transfer_3ea359c18e44b03b) }

var fileDescriptor_transfer_3ea359c18e44b03b = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x90, 0xcd, 0x4a, 0xc4, 0x40,
	0x10, 0x84, 0x4d, 0xf6, 0x47, 0x6c, 0xd9, 0x28, 0x8d, 0xc8, 0x20, 0x88, 0x92, 0x8b, 0x9e, 0xe6,
	0xa0, 0x0f, 0x20, 0xec, 0xc9, 0x83, 0x07, 0x09, 0x82, 0x47, 0x89, 0xd9, 0xce, 0x12, 0x70, 0xd2,
	0xb1, 0x67, 0x16, 0xf5, 0x75, 0x7c, 0x52, 0x77, 0x26, 0x33, 0x8a, 0x82, 0xb7, 0xfa, 0x8a, 0x6a,
	0x8a, 0x6a, 0x28, 0x9c, 0xd4, 0xbd, 0x6d, 0x49, 0xf4, 0x20, 0xec, 0x18, 0x8b, 0x96, 0xa5, 0xa1,
	0xa7, 0xe4, 0x96, 0x6f, 0x70, 0xf0, 0x10, 0x75, 0x45, 0xaf, 0x1b, 0xb2, 0x0e, 0x11, 0xa6, 0xad,
	0xb0, 0x51, 0xd9, 0x79, 0x76, 0xb9, 0x57, 0x05, 0x8d, 0x05, 0xe4, 0x8e, 0x55, 0x1e, 0x9c, 0xad,
	0xc2, 0x63, 0x98, 0xd7, 0x86, 0x37, 0xbd, 0x53, 0x93, 0xe0, 0x45, 0xf2, 0xb7, 0x86, 0x0c, 0xab,
	0xe9, 0x78, 0xeb, 0x35, 0x1e, 0xc1, 0xcc, 0xc9, 0x7b, 0xb7, 0x52, 0xb3, 0x60, 0x8e, 0x50, 0xde,
	0xc0, 0xe2, 0xa7, 0x78, 0x78, 0xf9, 0xf0, 0x31, 0xf1, 0x22, 0xf6, 0x8e, 0x80, 0x0a, 0x76, 0x0d,
	0x59, 0x5b, 0xaf, 0x29, 0xb6, 0x27, 0xbc, 0x6a, 0x60, 0xb1, 0x96, 0xa1, 0xf9, 0x9e, 0x82, 0x15,
	0x14, 0x9e, 0x2d, 0xf5, 0xab, 0xba, 0x71, 0x1d, 0xf7, 0x78, 0xa6, 0x7f, 0xaf, 0xd5, 0x7f, 0xa6,
	0x9e, 0x9c, 0xfe, 0x1f, 0xd8, 0x96, 0x97, 0x3b, 0xcb, 0x0b, 0x38, 0xec, 0x58, 0xfb, 0x1e, 0x9d,
	0x32, 0xcb, 0x7d, 0x62, 0x9b, 0xe0, 0x3e, 0xfb, 0xcc, 0x27, 0xb7, 0x77, 0x8f, 0xcf, 0xf3, 0xf0,
	0xde, 0xeb, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x76, 0xbb, 0x9e, 0xc9, 0x70, 0x01, 0x00, 0x00,
}
